In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.Tensor(5, 3)
print(x)


 0.0000 -2.0000 -0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000 -2.0000 -0.0000
[torch.FloatTensor of size 5x3]



In [5]:
x = torch.rand(5, 3)
print(x)


 0.4003  0.9484  0.9910
 0.2458  0.7670  0.2544
 0.6304  0.3170  0.4837
 0.6309  0.6198  0.5112
 0.7528  0.7672  0.8898
[torch.FloatTensor of size 5x3]



In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y = torch.rand(5, 3)
print(x + y)


 0.5399  1.2759  1.7998
 0.4055  1.1950  0.9063
 1.6040  1.2651  0.7693
 0.8813  1.1238  1.1187
 0.8247  1.0694  1.0880
[torch.FloatTensor of size 5x3]



In [8]:
print(torch.add(x, y))


 0.5399  1.2759  1.7998
 0.4055  1.1950  0.9063
 1.6040  1.2651  0.7693
 0.8813  1.1238  1.1187
 0.8247  1.0694  1.0880
[torch.FloatTensor of size 5x3]



In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.5399  1.2759  1.7998
 0.4055  1.1950  0.9063
 1.6040  1.2651  0.7693
 0.8813  1.1238  1.1187
 0.8247  1.0694  1.0880
[torch.FloatTensor of size 5x3]



In [10]:
y.add_(x)
print(y)


 0.5399  1.2759  1.7998
 0.4055  1.1950  0.9063
 1.6040  1.2651  0.7693
 0.8813  1.1238  1.1187
 0.8247  1.0694  1.0880
[torch.FloatTensor of size 5x3]



In [11]:
print(x[:, 1])


 0.9484
 0.7670
 0.3170
 0.6198
 0.7672
[torch.FloatTensor of size 5]



In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])

-1.0725 -0.6587 -0.8363 -1.6338
-1.3236  0.3445 -0.2469  1.5757
 0.4484 -1.4009 -0.3876  1.3690
 0.1752 -0.1120 -0.3818 -0.3489
[torch.FloatTensor of size 4x4]


-1.0725 -0.6587 -0.8363 -1.6338 -1.3236  0.3445 -0.2469  1.5757
 0.4484 -1.4009 -0.3876  1.3690  0.1752 -0.1120 -0.3818 -0.3489
[torch.FloatTensor of size 2x8]



In [25]:
a = torch.ones(3)
b = a.numpy() # share memory
a.add_(1)
b=b*2
print(a,b)


 2
 2
 2
[torch.FloatTensor of size 3]
 [4. 4. 4.]


In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)
a=a+1
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

[3. 3. 3. 3. 3.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [28]:
torch.cuda.is_available()

False